on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true
      - name: Install Dependencies
        run: bundle install
      - name: Build Static Site
        run: |
          bundle exec jekyll build \
          --destination preview \
          --config _config.yml,_config_pages.yml
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy preview --project-name=rails-website-preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
